#!/usr/bin/env python3
"""rawdb_sync.py — downstream sync from a RawDB instance to a local folder.

Mirrors approved sample files into <LOCAL_DIR>/<maker>/<model>/<path>
using the RawDB JSON export plus HTTP conditional GET
(If-Modified-Since) so unchanged files are not re-downloaded from S3.
No sidecar state file — the local file's mtime is the only sync state
we keep, stamped to the upstream Last-Modified on each successful
download.

Requires Python 3.11+. Pure stdlib.
"""

from __future__ import annotations

import argparse
import email.utils
import json
import os
import shutil
import ssl
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from pathlib import Path

# Files generated by the upstream rawdb_generator.py workflow. We never
# touch them on sync as long as their parent set still exists upstream.
SPECIAL_NAMES = {"rawdb-meta.toml", "LICENSE", "NOTES"}
CHUNK = 1024 * 1024  # 1 MiB stream buffer for downloads

# Serializes [RETRY] notification prints across worker threads. Sharing
# one module-level lock keeps notification ordering coherent without
# threading the lock through every call site.
_PRINT_LOCK = threading.Lock()


@dataclass
class FileEntry:
    maker: str
    model: str
    path: str
    size: int


@dataclass
class Counters:
    sets: int = 0
    files_seen: int = 0
    downloaded: int = 0
    bytes_downloaded: int = 0
    skipped: int = 0
    errors: int = 0
    pruned: int = 0
    lock: threading.Lock = field(default_factory=threading.Lock)


def human_bytes(n: int) -> str:
    s = float(n)
    for u in ("B", "KiB", "MiB", "GiB", "TiB"):
        if s < 1024 or u == "TiB":
            return f"{int(s)} B" if u == "B" else f"{s:.1f} {u}"
        s /= 1024
    return f"{n} B"


def parse_http_date(s: str) -> float | None:
    try:
        return email.utils.parsedate_to_datetime(s).timestamp()
    except (TypeError, ValueError):
        return None


def http_date(t: float) -> str:
    return email.utils.formatdate(t, usegmt=True)


def retry_after_seconds(headers, default: int) -> int:
    """Parse a Retry-After response header. Supports either an integer
    (seconds) or an HTTP-date; falls back to `default` if absent or
    unparseable. Always returns a value >= 1 second.
    """
    raw = headers.get("Retry-After") if headers else None
    if not raw:
        return max(1, default)
    raw = raw.strip()
    if raw.isdigit():
        return max(1, int(raw))
    # HTTP-date form: convert to a delta from now.
    ts = parse_http_date(raw)
    if ts is None:
        return max(1, default)
    delta = int(ts - time.time())
    return max(1, delta)


def open_with_429_retry(
    req: urllib.request.Request,
    *,
    ssl_ctx: ssl.SSLContext,
    retry_wait: int,
    display: str,
    timeout: float = 300.0,
):
    """`urlopen` that transparently retries forever on HTTP 429, honoring
    `Retry-After` and falling back to `retry_wait` seconds. Any other
    HTTPError (including 304 Not Modified) is propagated to the caller.
    """
    while True:
        try:
            return urllib.request.urlopen(req, context=ssl_ctx, timeout=timeout)
        except urllib.error.HTTPError as e:
            if e.code != 429:
                raise
            wait = retry_after_seconds(e.headers, default=retry_wait)
            with _PRINT_LOCK:
                print(f"[RETRY] {display}: HTTP 429, sleeping {wait}s")
            time.sleep(wait)


def build_download_url(base: str, maker: str, model: str, path: str) -> str:
    # Matches the frontend's api.downloadUrl: fully encode maker/model
    # segments, but preserve '/' inside the path (the axum route is
    # `/*path`, so the suffix may carry multiple segments).
    return (
        f"{base.rstrip('/')}/api/download/"
        f"{urllib.parse.quote(maker, safe='')}/"
        f"{urllib.parse.quote(model, safe='')}/"
        f"{urllib.parse.quote(path, safe='/')}"
    )


def fetch_export(
    base: str, api_key: str, ssl_ctx: ssl.SSLContext, retry_wait: int
) -> dict:
    req = urllib.request.Request(f"{base.rstrip('/')}/api/export")
    req.add_header("X-API-Key", api_key)
    req.add_header("Accept", "application/json")
    with open_with_429_retry(
        req,
        ssl_ctx=ssl_ctx,
        retry_wait=retry_wait,
        display="GET /api/export",
        timeout=120.0,
    ) as resp:
        return json.load(resp)


def sync_one(
    *,
    base: str,
    api_key: str,
    ssl_ctx: ssl.SSLContext,
    local_dir: Path,
    entry: FileEntry,
    dry_run: bool,
    retry_wait: int,
) -> tuple[str, int]:
    """Sync one file. Returns (action, bytes_downloaded).

    action ∈ {"download", "skip"}.  Raises on any other error so the
    caller can record it in the summary.
    """
    local = local_dir / entry.maker / entry.model / entry.path
    url = build_download_url(base, entry.maker, entry.model, entry.path)

    headers: dict[str, str] = {"X-API-Key": api_key, "Accept": "*/*"}
    if local.exists():
        st = local.stat()
        if st.st_size == entry.size:
            # Cheap-and-correct case: conditional GET. urllib follows the
            # backend's 302 to S3 carrying If-Modified-Since along; S3
            # honors it natively and returns 304 if unchanged.
            headers["If-Modified-Since"] = http_date(st.st_mtime)
        # If size differs, we deliberately omit If-Modified-Since so the
        # corrupted/truncated local copy gets overwritten unconditionally.

    if dry_run:
        # Don't hit the network in dry-run; classify by what the conditional
        # path would have done.
        if not local.exists():
            return ("download", 0)
        if local.stat().st_size != entry.size:
            return ("download", 0)
        return ("skip", 0)

    req = urllib.request.Request(url)
    for k, v in headers.items():
        req.add_header(k, v)

    display = f"{entry.maker}/{entry.model}/{entry.path}"
    try:
        resp = open_with_429_retry(
            req,
            ssl_ctx=ssl_ctx,
            retry_wait=retry_wait,
            display=display,
        )
    except urllib.error.HTTPError as e:
        if e.code == 304:
            return ("skip", 0)
        raise

    with resp:
        local.parent.mkdir(parents=True, exist_ok=True)
        partial = local.with_name(local.name + ".partial")
        bytes_written = 0
        try:
            with open(partial, "wb") as f:
                while True:
                    chunk = resp.read(CHUNK)
                    if not chunk:
                        break
                    f.write(chunk)
                    bytes_written += len(chunk)
            os.replace(partial, local)
        except BaseException:
            # Clean up the half-file on any failure (including KeyboardInterrupt).
            try:
                partial.unlink()
            except FileNotFoundError:
                pass
            raise

        # Stamp local mtime to the upstream Last-Modified so the next
        # sync's conditional GET works. If the header is missing or
        # unparseable, leave the OS-default mtime (now) in place.
        lm = resp.headers.get("Last-Modified")
        ts = parse_http_date(lm) if lm else None
        if ts is not None:
            os.utime(local, (time.time(), ts))

    return ("download", bytes_written)


def prune_or_count(
    *,
    local_dir: Path,
    expected: dict[tuple[str, str], set[str]],
    counters: Counters,
    delete: bool,
    verbose: bool,
) -> None:
    """Walk <LOCAL_DIR>/<maker>/<model>/ pairs and count (or remove)
    files that aren't in the export anymore.

    Rules:
      - Set still exists upstream → only stray files under it are
        candidates for deletion, and SPECIAL_NAMES never are.
      - Set gone upstream → the whole set directory is fair game,
        SPECIAL_NAMES included.

    `delete=False` counts only (and listing happens if `verbose=True`).
    """
    if not local_dir.exists():
        return
    tag = "PRUNE" if delete else "STRAGGLER"
    for maker_dir in sorted(p for p in local_dir.iterdir() if p.is_dir()):
        if maker_dir.name.startswith("."):
            continue
        for model_dir in sorted(p for p in maker_dir.iterdir() if p.is_dir()):
            key = (maker_dir.name, model_dir.name)
            if key not in expected:
                # Whole set removed upstream.
                files = [p for p in model_dir.rglob("*") if p.is_file()]
                for f in files:
                    if verbose:
                        print(f"[{tag}] {f.relative_to(local_dir).as_posix()}")
                    counters.pruned += 1
                if delete:
                    shutil.rmtree(model_dir, ignore_errors=True)
            else:
                want = expected[key]
                for f in list(model_dir.rglob("*")):
                    if not f.is_file():
                        continue
                    rel_in_set = f.relative_to(model_dir).as_posix()
                    if rel_in_set in want or f.name in SPECIAL_NAMES:
                        continue
                    if verbose:
                        print(f"[{tag}] {f.relative_to(local_dir).as_posix()}")
                    if delete:
                        try:
                            f.unlink()
                        except FileNotFoundError:
                            pass
                    counters.pruned += 1
            if delete:
                _rmdir_empty(model_dir)
        if delete:
            _rmdir_empty(maker_dir)


def _rmdir_empty(start: Path) -> None:
    if not start.exists():
        return
    # Deeper paths first so children are gone before parents.
    for d in sorted(
        (p for p in start.rglob("*") if p.is_dir()),
        key=lambda p: -len(p.parts),
    ):
        try:
            d.rmdir()
        except OSError:
            pass
    try:
        start.rmdir()
    except OSError:
        pass


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Sync a local samples folder with the RawDB online catalogue.",
    )
    ap.add_argument("local_dir", type=Path, help="Local mirror directory.")
    ap.add_argument(
        "--base-url",
        default=os.environ.get("RAWDB_BASE_URL"),
        help="RawDB base URL, e.g. https://rawdb.example.com (or env RAWDB_BASE_URL).",
    )
    ap.add_argument(
        "--delete",
        action="store_true",
        help="Remove local files that are no longer in the export.",
    )
    ap.add_argument(
        "-j",
        "--jobs",
        type=int,
        default=os.cpu_count() or 1,
        help="Parallel file workers (default: number of CPU cores).",
    )
    ap.add_argument(
        "--insecure",
        action="store_true",
        help="Skip TLS certificate verification (self-signed dev only).",
    )
    ap.add_argument(
        "-n",
        "--dry-run",
        action="store_true",
        help="Plan and print only; don't download or delete anything.",
    )
    ap.add_argument(
        "--retry-wait",
        type=int,
        default=60,
        metavar="SECS",
        help=(
            "Fallback wait (seconds) before retrying after HTTP 429 when "
            "the server's Retry-After header is missing or unparseable. "
            "When Retry-After is present, it always wins. Default: 60."
        ),
    )
    args = ap.parse_args()

    if args.jobs < 1:
        print("--jobs must be >= 1", file=sys.stderr)
        return 2
    if args.retry_wait < 1:
        print("--retry-wait must be >= 1", file=sys.stderr)
        return 2
    if not args.base_url:
        print(
            "--base-url or RAWDB_BASE_URL is required",
            file=sys.stderr,
        )
        return 2
    api_key = os.environ.get("RAWDB_API_KEY")
    if not api_key:
        print(
            "RAWDB_API_KEY environment variable is required",
            file=sys.stderr,
        )
        return 2

    ssl_ctx = (
        ssl._create_unverified_context()
        if args.insecure
        else ssl.create_default_context()
    )

    args.local_dir.mkdir(parents=True, exist_ok=True)

    try:
        export = fetch_export(args.base_url, api_key, ssl_ctx, args.retry_wait)
    except urllib.error.HTTPError as e:
        print(f"export fetch failed: HTTP {e.code} {e.reason}", file=sys.stderr)
        return 2
    except urllib.error.URLError as e:
        print(f"export fetch failed: {e.reason}", file=sys.stderr)
        return 2

    sets = export.get("sets") or []
    entries: list[FileEntry] = []
    expected: dict[tuple[str, str], set[str]] = {}
    for s in sets:
        maker = s["maker"]
        model = s["model"]
        paths = expected.setdefault((maker, model), set())
        for f in s.get("files") or []:
            entries.append(FileEntry(maker, model, f["path"], int(f["size"])))
            paths.add(f["path"])

    counters = Counters()
    counters.sets = len(sets)
    counters.files_seen = len(entries)
    total = len(entries)
    print(
        f"== rawdb_sync: {counters.sets} set(s), {total} file(s), "
        f"{args.jobs} worker(s){' [DRY-RUN]' if args.dry_run else ''} =="
    )

    print_lock = _PRINT_LOCK
    width = max(1, len(str(total)))

    if entries:
        with ThreadPoolExecutor(max_workers=args.jobs) as ex:
            futs = {
                ex.submit(
                    sync_one,
                    base=args.base_url,
                    api_key=api_key,
                    ssl_ctx=ssl_ctx,
                    local_dir=args.local_dir,
                    entry=e,
                    dry_run=args.dry_run,
                    retry_wait=args.retry_wait,
                ): e
                for e in entries
            }
            for fut in as_completed(futs):
                e = futs[fut]
                display = f"{e.maker}/{e.model}/{e.path}"
                try:
                    action, nbytes = fut.result()
                except Exception as exc:
                    with counters.lock:
                        counters.errors += 1
                    with print_lock:
                        print(f"[ERR] {display}: {exc}")
                    continue
                with counters.lock:
                    if action == "download":
                        counters.downloaded += 1
                        counters.bytes_downloaded += nbytes
                    else:
                        counters.skipped += 1
                    done = (
                        counters.downloaded + counters.skipped + counters.errors
                    )
                with print_lock:
                    if action == "download":
                        suffix = (
                            f"download  {human_bytes(nbytes)}"
                            if not args.dry_run
                            else "would download"
                        )
                    else:
                        suffix = "skip" if not args.dry_run else "up-to-date"
                    print(f"[{done:>{width}}/{total}] {display}  {suffix}")

    # Always count stragglers so the summary can hint at --delete; only
    # list them out loud when the user opted in (--delete or --dry-run).
    really_delete = args.delete and not args.dry_run
    prune_or_count(
        local_dir=args.local_dir,
        expected=expected,
        counters=counters,
        delete=really_delete,
        verbose=args.delete or args.dry_run,
    )

    print()
    print("== rawdb_sync summary ==")
    print(f"sets:        {counters.sets}")
    print(f"files seen:  {counters.files_seen}")
    print(
        f"downloaded:  {counters.downloaded}  "
        f"({human_bytes(counters.bytes_downloaded)})"
    )
    print(f"skipped:     {counters.skipped}")
    print(f"errors:      {counters.errors}")
    if args.delete:
        print(f"pruned:      {counters.pruned}")
    elif counters.pruned:
        print(
            f"stragglers:  {counters.pruned}  "
            f"(re-run with --delete to remove)"
        )

    return 1 if counters.errors else 0


if __name__ == "__main__":
    sys.exit(main())
