{{- if .Values.traefik.middlewares.enabled -}}
{{- $full := include "rawdb.fullname" . -}}
{{- $labels := include "rawdb.labels" . -}}
{{- if .Values.traefik.middlewares.rateLimit.enabled }}
{{- with .Values.traefik.middlewares.rateLimit }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $full }}-ratelimit
  labels: {{- $labels | nindent 4 }}
spec:
  rateLimit:
    average: {{ .average }}
    burst: {{ .burst }}
    period: {{ .period | quote }}
    {{- with .sourceCriterion }}
    sourceCriterion: {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- if .Values.traefik.middlewares.secureHeaders.enabled }}
{{- with .Values.traefik.middlewares.secureHeaders }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $full }}-secureheaders
  labels: {{- $labels | nindent 4 }}
spec:
  headers:
    browserXssFilter: {{ .browserXssFilter }}
    contentTypeNosniff: {{ .contentTypeNosniff }}
    frameDeny: {{ .frameDeny }}
    {{- with .referrerPolicy }}
    referrerPolicy: {{ . | quote }}
    {{- end }}
    stsSeconds: {{ .stsSeconds }}
    stsIncludeSubdomains: {{ .stsIncludeSubdomains }}
    stsPreload: {{ .stsPreload }}
    {{- with .contentSecurityPolicy }}
    contentSecurityPolicy: {{ . | quote }}
    {{- end }}
    {{- with .permissionsPolicy }}
    permissionsPolicy: {{ . | quote }}
    {{- end }}
    {{- with .customResponseHeaders }}
    customResponseHeaders: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .customRequestHeaders }}
    customRequestHeaders: {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- if .Values.traefik.middlewares.compression.enabled }}
{{- with .Values.traefik.middlewares.compression }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $full }}-compression
  labels: {{- $labels | nindent 4 }}
spec:
  compress:
    encodings: {{- toYaml .encodings | nindent 6 }}
    minResponseBodyBytes: {{ .minResponseBodyBytes }}
    {{- with .includedContentTypes }}
    includedContentTypes: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .excludedContentTypes }}
    excludedContentTypes: {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
