{{- if and .Values.gateway.enabled .Values.traefik.traefikService.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: {{ include "rawdb.fullname" . }}-weighted
  labels: {{- include "rawdb.labels" . | nindent 4 }}
spec:
  weighted:
    services:
      - name: {{ include "rawdb.fullname" . }}
        port: {{ .Values.service.port }}
        {{- with .Values.traefik.traefikService.weighted.weight }}
        weight: {{ . }}
        {{- end }}
    {{- with .Values.traefik.traefikService.weighted.sticky }}
    {{- if .enabled }}
    sticky:
      cookie:
        {{- with .cookie.name }}
        name: {{ . | quote }}
        {{- end }}
        secure: {{ .cookie.secure }}
        httpOnly: {{ .cookie.httpOnly }}
        {{- with .cookie.sameSite }}
        sameSite: {{ . }}
        {{- end }}
        {{- if gt (int .cookie.maxAge) 0 }}
        maxAge: {{ .cookie.maxAge }}
        {{- end }}
        {{- with .cookie.path }}
        path: {{ . | quote }}
        {{- end }}
        {{- with .cookie.domain }}
        domain: {{ . | quote }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
